### ISSUE TITLE
Roadmap to V2

### ISSUE THREAD

**Issue by janithcooray** [janithcooray/lin_os_swap_mod#26]
Following Needs to be implemented for V2 release. PRs are welcomed 

- [ ] Adjustable Swap Size and  Swapiness (#25 #21  )
- [ ] Select Swap path
- [ ] Multi Option Binary
- [ ] Fix Boot failure for some devices
- [ ] Log Reporter debuging (#23 )
- [ ] UI Manager ?

Hoping to Finish this by October
Any suggestions, please comment on this thread.
